name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    name: Test
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build Debug
      run: swift build -v
    
    - name: Run Tests
      run: swift test -v
  
  build-release:
    name: Build Release
    runs-on: macos-15
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build Release
      run: swift build -c release -v
    
    - name: Test Installation
      run: |
        swift package experimental-install
        # Verify the executable exists
        test -f ~/.swiftpm/bin/swift-mcp-gui