name: Swift Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode 16
      run: sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build Debug
      run: swift build -v
    
    - name: Build Release
      run: swift build -c release -v